AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM hello world

Resources:
  helloworldpython3:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler # filename: app.py
      Runtime: python3.8
      CodeUri: src/
      MemorySize: 128
      Timeout: 3
      Events: # this section adds API Gateway to the CloudFormation Stack
        HelloWorldSAMAPI:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
