@startmindmap mindmap

title Code&Slides download



*[#Orange] <b>Code&Slides download
 * Download code snippets archive\n//for CLI commands and certain services//
 * Download course slides
@endmindmap