@startmindmap mindmap

title EC2 Instance Storage

<style>
mindmapDiagram {
    .ebs {
        BackgroundColor  Violet
  }
}
</style>


*[#Orange] <b>EC2 Storages
 * <b>EBS vs EFS
  * <b>EBS\n*can be attached to only 1 EC2 instance at a time\n*bound to single Availability Zone\n*gp2: IO increases when volume size increases\n*io1: IO can be increased independently\n*to migrate to different Availability Zone:\n**take snapshot in source AZ\n**restore from snapshot in destination AZ\n*by default, root EBS volume is terminated\n   when owning EC2 instance is terminated\n*you pay for provisioned capacity
  * <b>EFS\n*can be mounted to 1000s of instances across AZ\n*good for sharing website files\n*can be only used with Linux(POSIX)\n*3x more expensive than EBS\n*can use EFS Infrequent Storage tier to save money\n*you pay only for used capacity
 left side
 * <b>EBS - Elastic Block Store\n*EBS is a network drive attached to EC2\n*normally, one EBS can be attached to only one EC2\n*EBS lives in a specified Availability Zone (eg. us-east-1a)\n**can be copied & cloned in form of Snapshot to another AZ\n*can be detached from one EC2 and attached to another EC2 quickly\n*Delete on Termination flag - to delete EBS when EC2 terminates <<ebs>>
 * <b>EBS Snapshot\n*snapshot is a volume backup copy that can be copied to another AZ\n*Snapshot Archive - can store snapshots 75% cheaper\n**but it takes 24-72 hours to restore <<ebs>>
 * <b>AMI - Amazon Machine Image\n*image with your own OS, software, configuration\n**pre-configured image = faster boot up\n*AMI lives in a specified Region\n**can be copied to another Region\n*there is a AMI Marketplace - with free and paid AMIs
 * <b>EC2 Instance Store\n*actual hardware disk attached to your EC2 instance\n*provides much for better performance - possibly 50x more IOPS\n*it is not a network drive like EBS\n*it's data is lost when EC2 is stopped - not a durable storage\n*good for buffer/cache/temporary content
 * <b>EBS volume types\n*gp2/gp3 (SSD) - general purpose volumes; good and cheap\n*io1/io2 (SSD) - highest performance volumes\n*st1 (HDD) - low cost volumes\n*sc1 (HDD) - lowest cost volumes\n*only gp2, gp3, io1 and io2 can be used as boot volumes\n*gp2 and gp3 can offer max 16k IOPS\n*io1 and io2 offer max 64k IOPS (Provisioned IOPS - PIOPS)<<ebs>>
 * <b>EBS multi-attach (io1,io2 volumes)\n*attach single EBS to multiple EC2 instances in the same AZ\n*each EC2 instance can read/write to the volume\n*must use filesystem that is cluster-aware<<ebs>>
 * <b>EFS - managed network file system\n*can be mounted on multiple EC2 instances\n*these EC2 instances can be in different Availability Zones\n*scalable, highly available, 3x more expensive than gp2\n*no need to provision capacity in advance\n*access is controlled with Security Groups\n*good for content management, data sharing, web serving\n*works only with Linux AMIs!!!\n*uses POSIX\n*encryption at rest using KMS\n*can handle thousands of clients, gigabytes per second throughput\n*Storage Tiers are available to save money on infrequent used files\n**Lifecycle Policy can automatically move files between tiers
@endmindmap