AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM hello world
Resources:
  helloworldpython3:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: s3://mateusz-demo-sam-bucket/234c7c37be6cc608c39400bf4825566f
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          TABLE_NAME:
            Ref: Table
          REGION_NAME:
            Ref: AWS::Region
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: Table
      Events:
        HelloWorldSAMAPI:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: greeting
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
