AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM hello world
Resources:
  helloworldpython3:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.8
      CodeUri: s3://mateusz-demo-sam-bucket/c529606ebb65f4427347ceacdb450eae
      MemorySize: 128
      Timeout: 3
